// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olehfhquezzfkdgilkut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sZWhmaHF1ZXp6ZmtkZ2lsa3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTk0MjYsImV4cCI6MjA2NzY3NTQyNn0.6v4G0dgxqDMgB398ojpUj9fkiiRtuCr3Nk-Pb9u2ogQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});